[phases.setup]
nixPkgs = ["python312Full"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

