[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

