[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "source /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source /app/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"

